- name: Add streamer init.d daemon script
  template: src=../../common/templates/init.d-template.j2 dest=/etc/init.d/streamer mode=0751

- name: Ensure streamer daemon is started
  service: name=streamer state=started